'use strict';

module.exports = {
  url: 'https://lumen.netlify.com',
  pathPrefix: '/',
  title: 'Bioinformatics Institute Publications',
  subtitle: 'Repository of all published Science Articles by our Researchers, their Group Members and Collaborators.',
  copyright: 'Bioinformatics Institute 2019 © All rights reserved.',
  disqusShortname: '',
  postsPerPage: 8,
  googleAnalyticsId: 'UA-73379983-2',
  useKatex: false,
  menu: [
    {
      label: 'Publications',
      path: '/'
    }
  ],
  author: {
    name: 'Bioinformatics Institute',
    photo: '/media/images/bii_logo_rgb_use-on-white-or-light-coloured-background.png',
    bio: 'Repository of all published Science Articles by our Researchers, their Group Members and Collaborators.',
    contacts: {
      email: '',
      facebook: '#',
      telegram: '',
      twitter: '#',
      github: '',
      rss: '',
      vkontakte: '',
      linkedin: '#',
      instagram: '#',
      line: '',
      gitlab: '',
      weibo: ''
    }
  },
  categories: [
    "Biomolecular Function Discovery Division",
    "Biomolecular Modelling and Design Division",
    "Imaging Informatics Division",
    "Translational Research Division",
    "Biomolecular Sequence To Function Division",
    "Biomolecular Structure To Mechanism Division",
    "Cellular Image Informatics Division",
    "Gene Function Prediction",
    "Protein Sequence Analysis",
    "Function and Structure of RNA",
    "Analytics of Biological Sequence Data",
    "Aging Biology Interventional Research",
    "Atomistic Simulations and Design in Biology",
    "Physics and Evolution of Biological Macromolecules",
    "Multiscale Simulation, Modelling and Design",
    "Structure-based Ligand Discovery and Design",
    "Computational Chemical biology and Fragment-based Design",
    "Algorithms and Models of Protein Machinery",
    "Computer Vision and Pattern Discovery for Bioimages",
    "Machine Learning for Bioimage Analysis",
    "Biophysical Modelling",
    "Complex Cellular Phenotype Analysis",
    "Clinical Data Analytics & Radiomics",
    "Natural Product Biology",
    "Natural Product Chemistry",
    "Chemical Genomics",
    "Antibody and Product Development",
    "BioMedical Data Architecture & Repository",
    "Clinical Data Engagement",
    "Research Data Integration",
    "Algorithms and Models of Protein Machinery",
    "Genome & Gene Expression Data Analysis",
    "Spatial & Single-Cell Omics Immunology",
    "Molecular Innovations And AI Integrations",
  ],
};
