backend:
  name: git-gateway
  branch: master

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Journal ", name: "journal", widget: "string"}
      - {label: "Pubmed ", name: "pubmed", widget: "string"}
      - {label: "URL ", name: "url", widget: "string"}
      - {label: "Impact Factor", name: "impactfactor", widget: "string"}
      - {label: "Date of Acceptance", name: "dateofacceptance", widget: "datetime"}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Author", name: "tags", widget: "list"}
      - {label: "Group", name: "categories", widget: "list"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}